fix: Update instance template version to cloudbees-poc-it-0.0.741
The cse provider is now deprecated and possibly no longer used, the installation tag is also now far more in the future and is not ideal
```
lastTransitionTime: "2020-01-23T10:07:54Z"
      message: "error waiting for create operation to complete on SLM resource \"projects/821953514171/locations/us-east1/instances/168841630839--jx\":
        operation projects/821953514171/locations/us-east1/operations/operation-1579771552974-59ccb3a3dc525-beed1746-5d84b7f4
        returned error code: 10, message: Operation failed with error: \ngeneric::invalid_argument:
        terraform apply failed, error: exit status 1, stderr: \n\nError: retry timed
        out at \"2020-01-23 01:59:37.237349299 -0800 PST m=+2009.801496684\". last
        error: output (\"started\") doesn't match the expected target (\"finished\")\n\n
        \ on cse.tf line 46, in data \"cse_kube_resource\" \"service\":\n  46: data
```